agent_name: Structure_rag_hippo_rag_v2_nv
model: Qwen/Qwen3-4B-Instruct-2507
tokenizer_model: Qwen/Qwen3-4B-Instruct-2507
provider: openai_compatible
api_base: http://127.0.0.1:8000/v1
api_key: EMPTY
temperature: 0.7
input_length_limit: 262144
buffer_length: 200
output_dir: ./outputs/qwen3-4b-vllm-hippo_rag_v2_nv

retrieve_num: 10

hipporag_embedding_model: nvidia/NV-Embed-v2
hipporag_embedding_batch_size: 8
hipporag_embedding_max_seq_len: 2048
hipporag_max_new_tokens: 2048
hipporag_retrieval_top_k: 200
hipporag_linking_top_k: 5
hipporag_qa_top_k: 10
hipporag_openie_mode: online
